version: '3'
services:

  node-app:
    build: 
      context: .
      args:
        - NODE_ENV=development
        - MONGO_USER=kamran
        - MONGO_PASSWORD=khan
        - SESSION_SECRET=secret
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev